language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

services:
  - cassandra
  - mongodb
  - redis
  - elasticsearch
  - rabbitmq

before_install:
    # Neo4j 2.2 install
    - wget dist.neo4j.org/neo4j-community-2.2.0-unix.tar.gz
    - tar -xzf neo4j-community-2.2.0-unix.tar.gz
    - sed -i.bak s/dbms.security.auth_enabled=true/dbms.security.auth_enabled=false/g neo4j-community-2.2.0/conf/neo4j-server.properties
    - neo4j-community-2.2.0/bin/neo4j start
    # Mongo Driver
    - wget http://pecl.php.net/get/mongo-1.2.10.tgz && tar -xzf mongo-1.2.10.tgz && sh -c "cd mongo-1.2.10 && phpize && ./configure && sudo make install" && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

##USE THRIFT WITH CASSANDRA
before_script:
  - composer install

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
    

source_key: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBcDhncTFOa2FoS3M1RkRUS1VzT1QrTXFVTVJCMVV0VDdJUG1WSWV0QmV2M1AzYmVrClJwVysxRWJIWEJmaFhoQXBTK3BHYjZVOEUveDNYSEtyWlozWDdzTmlobEM1UVZ2NE5ReEdJbGJSdmh0VVI0UWIKMXpPTER1MmtSQXpVa3FWWExVSGpoN3ZwZmFkUEI2MmR6N3dycnlpaDN5d2RWVUloOVBJUlNGd0xnZ3UvYTlObgpTUUdleFpndUVwOXhRMmdCUDFQei9sWUh5L2t1d2l3dHZnVDFsa2lIVlJwaVhxcTF1QTNGd09KY3NaVnhPQUd0CkNoU2hDVXVvVlJNL1YzWnd0NmdLd3lhcGhkbWFrUXJHTFh3VlR1REtEYmNYWFV3QVRDeVUvRTlxdDBlTEZiWnYKRHc1UEtsY0E1SkJmVzVtSWFVcytMUEtQZ0Zud1UwVGZiNHVhM1FJREFRQUJBb0lCQUhrOGpwYVcraTU3ZXhjNgp2aWZuNHZpWGlWV2F5dXc3c2VzMTdhbEEwV1FLR3pYZkNQbG9JeWhJckszREk3cFFlMGE3MW9HK0tCZFpDdmJtCmRTdE1UMGZjTDBsVzgwWmpLb3RLZnpNNUFQNFp5V0NUK1hvYmFKUTA2OG13YTdvN2R5N2d1WVRQSi96LzlIOWIKMlBqT3c5SWh6alh4THBENDVJaVdraDV6UkcyRzIrMGZzTnBXeVNKZThtQlhVTjN0Q1FlaGxERlQyZnFxTnZOcQpRbjhKdGR5YlhWVG9wR1RSSXBOUjdORExBdCtzWmhHT2pOV1N1UHVvOGNpcjJpTU5UUzJtYlFWdkJsbVJCMjNSCmtORmRHQ0VwQlZzM1lXUWxqOXlaVkcwbVlNaGdBTmZPTjgvS2ZVak5JSytXRXBsaXNzQmJaQ0pzQUhYM3U2WXYKQ2VWTGhJRUNnWUVBMXBOZHpuSTR3alJEMnJkVFo5d1UrTzhNYko2cm5sb2xrckMwNE9rYkNQM3hsRFdZNUhVMwpRSUdZOHVrblh4Y2RFNWNrV29Ja3NGdURtK0pNNnV2NEZVcUw5d0l3VFVBVlFoc2pnRm8wRktxa1F1blZIZnRXClBUeGxDejFGWjlEN094dWc3VzdZTHFWdWlmU0F1Tjd5QXFmallmY01TRDhwRGwvVm5ZNUlpemtDZ1lFQXlDd3YKK3YrY2xHSGpHZWd2cm82Sis3bWk2Uk1JTE1iNmkzUGVKd3hyaDhDZUZKSzBjNFpYck0zY2E3bzNJZldqZVRXVwpWMSs5M2ppZGZHSmFpeGNEaU9KbHU5cnVqamd3Mkx5eGRaam93OGZ1TnoyQXBNdFdNOVorRStLU3FUdmhJOWd1Cit4aHliZE9yVTdzY3JXNVZLSFNXYnpmeitOWmV2TG9DZ3psa09NVUNnWUE0V0NBRXl0ZCtuMnpGN09lNDJRQ2sKMFZpbzJRMWxtblJOVFp0aGg3Unlxd1FaaisxaTZDaW5CcURjQUQ4M2FBRlptSkdTTnFSZHJ0b2pQOHhFejh1bwpBNWczTjFycG5nODIrWnRiNDlQVExXL09wa294QWtPRjl1cnRoWnhKQTRaRTRoOWkyWDFvMmtYcGNjdXZQOU82CndNMGpkMVRCVDl4L0NzazBBeDJuZVFLQmdHVFo5bmFVY0ZSR0dVQ0ZQZmpKY2ZXMHFzS1pSeVlnUGowaWJJdnAKOHdkYllZbmwvQ3EwUmRvWGdmVjR4YXhEY1ZCeFVrVEZSUWtBSjBCeTRVRnduK1JJaEk4b0Y4YnB3cHFBUHp5TApoTUtYS1lzRlhwb29wRTdMdzR2TFBLOHRMeHA3SWZoNmNiU3B6NGtKSGNLM2N3cEY2MEV2eEtqYmdMRy9XZUs1CmVLZ3RBb0dCQUt4di9EaVROZ3pObEdIZ1hqeldJSnB4aG0wc3ZNc2pXRm0zRDZOYUpLcmdBU3VyWDFmQ3lwcHUKcml5NjFjNXNDY1JpQ21LTlViU2hiUWtVdmZ1VG5PQmJBeDFLQVRCcUlnV0Q3dmVjekRjWUtUMWx3U0RHSG14SgpGQXhKWVdad2N5VUNrbXcvVnNzSEVQL1hwbnM4RTA3N3pZTUVCeVRaQnB1ZkFnU2VVWTRwCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg=="
